-- auto-generated definition
create table stevne
(
    stevne_id   bigint generated by default as identity
        constraint table_name_pkey
            primary key,
    user_id     uuid                                                              not null
        constraint stevne_user_id_fkey
            references auth.users,
    navn        text                                                              not null,
    fra_dato    timestamp,
    til_dato    timestamp,
    kommentar   text,
    inserted_at timestamp with time zone default (now() AT TIME ZONE 'utc'::text) not null,
    updated_at  timestamp with time zone default (now() AT TIME ZONE 'utc'::text) not null
);

alter table stevne
    owner to supabase_admin;

grant delete, insert, references, select, trigger, truncate, update on stevne to postgres;

grant delete, insert, references, select, trigger, truncate, update on stevne to anon;

grant delete, insert, references, select, trigger, truncate, update on stevne to authenticated;

grant delete, insert, references, select, trigger, truncate, update on stevne to service_role;

